### PR TITLE
Check log multithread safeness

### LINKED ISSUE #92: Test log thread-safeness
The documentation now explains the guarantees it should cover.

### PR DESCRIPTION
**Pull request by seppo0010**
Fixes #92

### CODE REVIEW

**Comment by thinkingfish** [comment]
The thread execution order of this test is not deterministic. The consumer thread may never try to flush/reopen the logger _while_ the producer is actively writing, which is the interesting case. So the value of the test (as a unit test, not a probabilistic test) is limited.

It's hard to test contention without sort of _break open_ the implementation. In this case, what we really want to know is if a flush happens while the write to log buffer is happening, what gets flushed to the file and what is not, and whether we would miss/duplicate anything as a result.

The general opinion about testing race conditions is rather pessimistic:
http://programmers.stackexchange.com/questions/196105/testing-multi-threaded-race-conditions
and the creation of a race condition is generally intrusive (to the module we are testing):
http://www.informit.com/articles/article.aspx?p=1882162

I'm interested in some kind of formal verification for some of the thread-safety claims we make in various modules, but I haven't spent much time setting up yet.

**Comment by paegun** [comment]
@thinkingfish the general opinion about testing race conditions is generally considering only what can be done w/i the system under test and test. So the general opinion is leaving out the testing framework and/or compiler-provided tools. Since clang is used, if present, TSan ( http://clang.llvm.org/docs/ThreadSanitizer.html ) should be considered.

**Comment by thinkingfish** [comment]
@paegun Interesting tool. But seems it doesn't support libc? Any experience using it with a C codebase?

**Comment by paegun** [comment]
@thinkingfish I think the tsan documentation leads too much towards c++11, but clang (C) and clang++(C++) both have tsan integration. I've posted the following gist which demonstrates via a small example tsan in C: https://gist.github.com/785c726acf592ef91137bd90614e1ede

If I'm not understanding "doesn't support libc" properly, sorry. My experience w/ tsan in a C codebase has been limited to portability only to a few linux variants.

**Comment by thinkingfish** [comment]
Great! I'll look into it. Mostly, since Twitter doesn't officially support Clang, I need to think about how to integrate this into the build/test flow.

**Comment by paegun** [comment]
@thinkingfish I've updated the gist to include gcc 4.8 and the undocumented bits required to use tsan.

@seppo0010 sorry for the general thread testing commentary on this specific PR, which looks great.

**Pull request closed without merging**
